### ISSUE TITLE
Link mancante autodichiarazione

### ISSUE THREAD

**Issue by andrearavalli** [ministero-salute/it-dgc-verificac19-sdk-onboarding#1]
Buongiorno,
il link -> https://github.com/ministero-salute/it-dgc-verificac19-sdk-onboarding/blob/main/autodichiarazione.odt da come risultato 404.

**Comment by ministerosalute** [comment]
Fixed by https://github.com/ministero-salute/it-dgc-verificac19-sdk-onboarding/commit/ae1057e37c80e9ef0f732a16371555b1dc58f8d3, thanks @andrearavalli
