### ISSUE TITLE
Test suite ufficiale

### ISSUE THREAD

**Issue by lu-zero** [ministero-salute/it-dgc-verificac19-sdk-onboarding#12]
Per l'implementazione [rust](https://github.com/rust-italia/dgc) stiamo usando [dgc-testdata](https://github.com/eu-digital-green-certificates/dgc-testdata).

Contate di fornire una test-suite specifica per `verificac19` ?

**Comment by astagi** [comment]
Ciao @lu-zero al momento non è previsto niente di simile, puoi comunque far riferimento al [SDK in NodeJS](https://github.com/italia/verificac19-sdk) che copre i casi necessari (stiamo lavorando adesso per portare anche la modalità booster)
