### ISSUE TITLE
QUESTION: DGC rafforzato per gli over 50

### ISSUE THREAD

**Issue by Elius94** [ministero-salute/it-dgc-verificac19-sdk-onboarding#22]
Ciao a tutti, mi chiedevo se in merito alla modifica che avverrà a partire da febbraio sarà necessario verificare a valle delle SDK se l'età dell'utente è inferiore a 50 anni, in modo da applicare la verifica rafforzata solo in caso negativo.

https://www.dgc.gov.it/web/?tick=64481411

Esempio: devo realizzare un sw per un'azienda e il controllo da fare è sempre quello base attualmente (entrano anche i non vaccinati con tampone), tuttavia dal 15 febbraio se la persona con DGC antigenico o molecolare dovesse provare ad entrare, bisognerebbe applicare la regola del super DGC. 
Non ho capito se è un controllo che viene fatto in automatico seguendo le rules statali  o se in questo caso è da fare a livello applicativo.
Grazie

**Comment by DevPGS** [comment]
Ciao @Elius94,
sono iniziati i primi commit su branch dedicata per questa modifica:[feature/work-scan-mode]( https://github.com/ministero-salute/it-dgc-verificac19-sdk-android/tree/feature/work-scan-mode) , quindi presumibilmente il controllo verrà fatto lato SDK, mentre lato applicativo sarà necessario impostare il corretto scanMode da utilizzare.

**Comment by Elius94** [comment]
Ok, perfetto, tengo monitorato. Grazie mille
