### ISSUE TITLE
Se una libreria viene pubblicata nel readme e a tutti gli effetti valida secondo il DCPM?

### ISSUE THREAD

**Issue by FrancescoBonizzi** [ministero-salute/it-dgc-verificac19-sdk-onboarding#5]
Buongiorno, ho letto il readme di questo repo, ma chiedo ugualmente conferma: se una pull viene accettate e la libreria risulta pubblicata e linkata nella tabella del Readme, essa diventa automaticamente valida ai fini della verifica del Green Pass al pari dell'SDK Android?

**Comment by rawmain** [comment]
Buongiorno @FrancescoBonizzi

> se una pull viene accettate e la libreria risulta pubblicata e linkata nella tabella del Readme, essa diventa automaticamente valida ai fini della verifica del Green Pass al pari dell'SDK Android? 

L'esito positivo in validazione di SDK/librerie di terze parti conferma appunto la loro aderenza a specifiche tecniche + requisiti minimi & la conformità con SDK ufficiali di riferimento (ved. SDK Android/Kotlin), come previsto da art. 12 [DPCM 12/10/2021](https://www.governo.it/sites/governo.it/files/DPCM_12_ottobre.pdf) .

> 12. Il pacchetto di sviluppo per applicazioni di cui alla lettera a) del comma 10 può essere utilizzato per la verifica della Certificazione verde COVID-19 anche in ambiti diversi da quello lavorativo e può altresì essere utilizzato come riferimento per la realizzazione di ulteriori librerie software, a condizione che:
>

> - a) le suddette librerie e le soluzioni da esse derivate rispondano alle medesime specifiche tecniche e ai requisiti del pacchetto di sviluppo per applicazioni di cui alla lettera a) del comma 10, e successivi aggiornamenti, come indicato sulla piattaforma utilizzata dal Ministero della Salute per la pubblicazione del codice sorgente;
>
> - b) sia preventivamente rilasciato il codice sorgente con licenza open source di dette librerie sulla piattaforma utilizzata dal Ministero della Salute di cui al precedente punto a).

Pertanto, la risposta è SI.

SDK/librerie di terze parti, una volta ufficialmente inserite/presenti in lista Ministero Salute in virtù di OK validazione, potranno essere usate in modo regolare/autorizzato per sviluppo+rilascio di soluzioni verifier terze & conformi a condizioni trattamento DGC/dati ex art. 13 DPCM 12/10/2021.

> 13. Con riguardo all’uso del pacchetto di sviluppo per applicazioni, di cui al comma 10, lettera a), e delle librerie software e delle soluzioni da esse derivate, di cui al comma 12, il trattamento dei dati personali deve essere effettuato limitatamente alle informazioni pertinenti e alle operazioni strettamente necessarie alla verifica della validità delle Certificazioni verdi COVID-19. 
>
> - È fatto esplicito divieto di conservare il codice a barre bidimensionale (QR code) delle Certificazioni verdi COVID-19 sottoposte a verifica, nonché di estrarre, consultare, registrare o comunque trattare per finalità ulteriori rispetto a quelle previste dal presente articolo le informazioni rilevate dalla lettura dei QR code e le informazioni fornite in esito ai controlli. 
>
> - In caso di utilizzo di tale modalità di verifica da parte del datore di lavoro, resta salvo quanto previsto dagli articoli 88 del Regolamento (UE) 2016/679 e 113 del decreto legislativo 30 giugno 2003, n. 196.

Ovviamente, la permanenza in lista - cioè il mantenimento dello status OK post validazione iniziale - dipende dall'allineamento con gli aggiornamenti lato SDK ufficiali & con i requisiti di conformità (_ved. policy Accettazione/Rimozione in Readme_).
